source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'RSS' do
    pod 'PureLayout'
    pod 'FontAwesomeKit'
    pod 'IQKeyboardManager'
    pod 'STPopup'
    pod 'SwiftOverlays'
    pod 'ESPullToRefresh'
    pod 'DZNEmptyDataSet'
    pod 'GrowingTextView'
    pod 'INSPhotoGallery'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Messaging'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'GoogleMaps'
    pod 'SDWebImage'
    pod 'Alamofire'
    pod 'BNHtmlPdfKit'
end
